##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-cafe-team/cafe-calc
    - autoconf
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - expect #required for unbuffer
    - gcc
    - gettext
    - git
    - libatk1.0-dev
    - libglib2.0-dev
    - libxml2-dev
    - make
    - wget
    - yelp-tools

    #packages required for ctk
    - adwaita-icon-theme
    - dconf-gsettings-backend
    - hicolor-icon-theme
    - libatk-bridge2.0-dev
    - libatk-bridge2.0-0
    - libcolord2
    - libcups2
    - libegl1-mesa-dev
    - libepoxy0
    - libepoxy-dev
    - libfontconfig1-dev
    - libfribidi-dev
    - libgdk-pixbuf2.0-dev
    - libjson-glib-1.0-0
    - libpango1.0-dev
    - librest-0.7-0
    - libwayland-dev
    - libx11-dev
    - libxcomposite-dev
    - libxcursor-dev
    - libxdamage-dev
    - libxext-dev
    - libxfixes-dev
    - libxi-dev
    - libxinerama-dev
    - libxkbcommon-dev
    - libxrandr-dev
    - wayland-protocols

before_scripts:
  - ./html-cppcheck
  - ./install-from-git https://github.com/cafe-desktop/cafe-common master

  # Install required ctk .deb packages
  - git clone https://github.com/cafe-desktop/ctk.git -b master ctk-master
  - cd ctk-master
  - wget https://github.com/cafe-desktop/ctk/releases/download/`git describe --abbrev=0 --tags`/libctk-3-dev_`git describe --abbrev=0 --tags|sed 's/^.//'`-1_amd64.deb
  - wget https://github.com/cafe-desktop/ctk/releases/download/`git describe --abbrev=0 --tags`/gir1.2-ctk-3.0_`git describe --abbrev=0 --tags|sed 's/^.//'`-1_amd64.deb
  - wget https://github.com/cafe-desktop/ctk/releases/download/`git describe --abbrev=0 --tags`/libctk-3-common_`git describe --abbrev=0 --tags|sed 's/^.//'`-1_all.deb
  - wget https://github.com/cafe-desktop/ctk/releases/download/`git describe --abbrev=0 --tags`/libctk-3-0_`git describe --abbrev=0 --tags|sed 's/^.//'`-1_amd64.deb
  - dpkg -i *.deb
  - cd ..
  - rm -rf ctk-master

build_scripts:
  - ./before-build
  - ./make-scanbuild '--enable-compile-warnings=maximum'
  - ./after-build

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20; fi
