.\" Man page for cafe-calc
.TH CAFE-CALC 1 "1 February 2014" "CAFE Desktop Environment"
.\" Please adjust this date when revising the manpage.
.\"
.SH "NAME"
cafe-calc \- (cafe-calculator) \- The CAFE Desktop Environment Calculator
.SH "SYNOPSIS"
.B cafe-calc [OPTIONS...] [FILES...]
.SH "DESCRIPTION"
\fBcafe-calc\fR is the official calculator for the CAFE Desktop Environment. It has been designed to be used with either the mouse or the keyboard. It is visually similar to a lot of hand-held calculators.
.PP
This manual page briefly documents the \fBcafe-calc\fR command.
.SH "OPTIONS"
.TP
\fB\-s, \-\-solve\fR <equation>
Solve the equation provided following this option.
.TP
\fB\-\-version\fR
Output version information and exit.
.TP
\fB\-h, \-?, \-\-help\fR
Print standard command line options.
.TP
\fB\-\-help\-all\fR
Print all command line options.
.P
This program also accepts the standard CTK options.
.SH "EXAMPLES"
\fBcafe-calc \-s 4*10.5\fR
.RS 4
Multiply 4 by 10.5
.RE
.PP
\fBcafe-calc \-s 21+21\fR
.RS 4
Add 21 plus 21
.RE
.PP
\fBcafe-calc \-\-solve '((5.25×4)×2)'\fR
.RS 4
Multiply 5.25 by 4 and their product by 2
.RE
.PP
\fBcafe-calc
.RS 4
Open the Calculator GUI.
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at: 
http://github.com/cafe-desktop/cafe-calc/issues
.SH "AUTHORS"
.SS This Man Page has been written for the CAFE Desktop Environment by:
Adam Erdman <hekel@archlinux.info> (2014)
.SH "SEE ALSO"
.SS
cafe-calc documentation can be found from the "Help" menu, or by pressing the F1 key. 
Further information may also be available at: http://wiki.cafe-desktop.org/docs
.P
.BR cafe-calc-cmd (1)
